name: 'Deployment Status Update'
description: 'Updates your Deployment status in GitHub to a desired one'
author: 'Rostyslav Sotnychenko'
branding:
  icon: 'rss'
  color: 'gray-dark'
inputs:
  run_id:
    description: 'Set this to `github.run_id` so the deployment status log URL can be properly set.'
    required: true
  status:
    description: 'desired deployment status'
    required: true
  description:
    default: ''
    description: 'description to deployment status'
  auto_inactive:
    default: true
    description: 'Adds a new inactive status to all prior non-transient, non-production environment deployments with the same repository and environment name as the created deployment status.'
  environment_url:
    default: ''
    description: 'Sets the URL for accessing your environment'
  deployment_status_url:
    description: Override the default deployment status URL.
outputs:
  deployment_id:
    description: 'An ID of the deployment in GitHub'
  description:
    description: 'Description of the deployment'
  state:
    description: 'Deployment state'
  ref:
    description: 'Branch/tag name of the deployment source'
  sha:
    description: 'Revision of the deployment source'
  environment:
    description: 'Environment name'
  payload:
    description: 'Payload'
runs:
  using: 'docker'
  image: 'Dockerfile'

